version: "3.9"
services:
    web:
        image: nginx:alpine
        ports:
            - "9000:80"
        depends_on:
            - "app"
        volumes:
            - ./web/conf.d:/etc/nginx/conf.d:ro
    app:
        build:
            context: "."
            dockerfile: "Dockerfile"
        user: "${UID}:${GID}"
        volumes:
            - "./prox:/opt/app"
        command:
            - "uvicorn"
            - "main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--reload"
