version: "3.9"
services:
    web:
        image: nginx:alpine
        ports:
            - "9000:80"
        depends_on:
            - "app"
            - "front"
        volumes:
            - ./web/conf.d:/etc/nginx/conf.d:ro
    app:
        env_file:
            - "app.env"
            - ".env"
        build:
            context: "."
            dockerfile: "Dockerfile"
        user: "${UID}:${GID}"
        volumes:
            - "./prox:/opt/app"
        command:
            - "uvicorn"
            - "main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--reload"
    front:
        image: node:14.15.3-alpine
        env_file:
            - "front.env"
        environment:
            - "CHOKIDAR_USEPOLLING=true"
            - "API_URL=http://app:8000/sankaku"
        volumes:
            - "./front:/opt/app"
        working_dir: /opt/app
        command: [sh, -c, npm install && npm run build && npm run dev]
        ports:
        - "3000:3000"
        depends_on:
            - "app"
