import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getAll } from '../lib/api'
import Gazou from '../components/gazou'
import Modal from '../components/modal'
import { useEffect, useState } from 'react'

export default function Home() {
  const loadingFigure = {type: "loading", href: "", src: ""}
  const [loaded, setLoaded] = useState(false)
  const [requesting, setRequesting] = useState(false)
  const [page, setPage] = useState(0)
  const [showModal, setShowModal] = useState(false)
  const [pickUpPost, setPickUpPost] = useState({})
  const [posts, setPosts] = useState([...Array(10)].map(() => loadingFigure))

  async function nextFetch(page) {
    const IMAGE_API = process.env.NEXT_PUBLIC_IMAGE_API
    const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT

    const query_params = new URLSearchParams({page})
    const res = await fetch(API_ENDPOINT + "/sankaku" + "?" + query_params, {
      method: 'GET',
    })
    const json = await res.json()
    if (json.errors) {
      console.error(json.errors)
      throw new Error('Failed to fetch API')
    }
    return json.body.map((post) => {
        post.src = IMAGE_API + "?path=" + encodeURIComponent(post.src)
        return post
    })
  }
  const next = async () => {
    setRequesting(true)
    setPosts(Array.prototype.concat(posts, [...Array(10)].map(() => loadingFigure)))
    console.log(posts);
    const newPosts = (await nextFetch(page + 1)).map(v => {return {type: "loaded", ...v}})
    const all = Array.prototype.concat(posts.filter(v => v.type === "loaded"), newPosts)
    setPosts(all)
    setPage(page + 1)
    setRequesting(false)
  }
  useEffect(async () => {
    if (!loaded) {
      setLoaded(true)
      await next()
    }
  })

  function openModal(e, post) {
    e.stopPropagation()
    e.preventDefault()
    setShowModal(true)
    setPickUpPost(post)
    console.log(post)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post, idx) => {
          return (
            <Gazou
              key={`${idx}${post.href}`}
              type={post.type}
              href={post.href}
              src={post.src}
              handleClick={e => {
                openModal(e, post)
              }}
            />
          )
        })}
        {showModal && (
          <Modal
            handleClose={() => {
              setShowModal(false)
              setPickUpPost(undefined)
            }}
          >
            {pickUpPost && (
              /* eslint-disable */
                <img src={pickUpPost.src}/>
              /* eslint-enable */
            )}
          </Modal>
        )}
      </main>
      <section>
        <button className={styles.button} onClick={async () => await next()} disabled={requesting}>go to {page + 1}</button>
      </section>
    </div>
  )
}

export async function getServerSideProps() {
  // const allPosts = await getAll()
  return {
    props: {},
  }
}
