import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getAll } from '../lib/api'
import Image from '../components/Image.jsx'

export default function Home({allPosts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* eslint-disable */}
          {allPosts.map((post, idx) => {
            return <figure key={idx}><a href={post.href} title={post.href}><Image src={post.src} /></a></figure>
          })}
        {/* eslint-enable */}
      </main>

      <footer className={styles.footer}>
        Powered by hogeho
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const allPosts = await getAll()
  return {
    props: { allPosts },
  }
}
